### ISSUE TITLE
Error 500 When I run the project.

### ISSUE THREAD

**Issue by deepakshantilalshah** [MicroPyramid/Django-CRM#110]
Here are the steps I followed:

1. Installed Requirements.txt
2. Added DB - dj_crm (as indicated in the settings.py file). 

When I run the server, it throws the following error:

> 500
> The page you're looking for could not be found.
> Make sure the address is correct and that the page hasn't moved.
> 
> Please contact your GitLab administrator if you think this is a mistake.
> 
> GO back Home CRM Home

What should be done in this case?

**Comment by nikhila05** [comment]
@deepakshantilalshah, check if you've installed pre requirements like **sass** in your system.

For local development, you can use manage_local.py file and can run the project using the following command.

**`python manage_local.py runserver`**

**Comment by deepakshantilalshah** [comment]
I have run requirements.txt and also added installed sass. Now, it keeps showing me error 500, with this error. 

`  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "contacts_contact_email_b008e8f9_uniq" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/migrations/operations/models.py", line 514, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 360, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/deepak/djangoprojects/DjangoCRM/CRM/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "contacts_contact_email_b008e8f9_uniq" already exists
`
I am sorry if it's a noob mistake, and thanks in advance.
