### ISSUE TITLE
Scoket Error in Marketing section.

### ISSUE THREAD

**Issue by AceScottie** [MicroPyramid/Django-CRM#312]
```Python
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 94, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\util\retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connection.py", line 183, in connect
    conn = self._new_conn()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0B223EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
Failed to query Elasticsearch using 'is_bounced:(true)': ConnectionError(<urllib3.connection.HTTPConnection object at 0x0B223EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x0B223EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 94, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\util\retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connection.py", line 183, in connect
    conn = self._new_conn()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0B223EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

```

This repeats untill i close the server, even if i naviagate away the error continues on the server and the client is slowed (but other areas still work).

The issue is only on "Contacts List" and "Contacts" sections on the "Marketing" All other aspects work

This may be just for me as i am editing to allow custome titles set in settings
adding:

    contex["TITLE"] = settings.TITLE
    or:
    contex({'TITLE': settings.TITLE, etc...})

To views.py where contect is created. and setting TITLE = "MyApp CRM" in the settings.py file.
As a note on that i am having some issues transfering the TITLE context to the Marketing secions. "all.html", "base.html" and "root.html" are not accepting {TITLE} in the Marketing section but Sales section works fine. Could do with having a chat on Gitter about this if you are availble at any point.

**Comment by vineeshan** [comment]
@AceScottie Please install elasticsearch to resolve that issue.
