### ISSUE TITLE
The SECRET_KEY setting must not be empty

### ISSUE THREAD

**Issue by chaharnitesh** [MicroPyramid/Django-CRM#402]
I tried to find this bug, but don't know how to solve it.getting error message "The SECRET_KEY setting must not be empty." when executing python manage.py runserver

Here is the full error message:

Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/cipher/environment/admin/lib/python3.8/site-packages/django/conf/__init__.py", line 161, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by Singhisbling** [comment]
Have you set the environment variable SECRET_KEY in .env file?

**Comment by chaharnitesh** [comment]
Yes, I have set the environment variable and also specify the path in settings.py file but still got the same issue.

**Comment by Singhisbling** [comment]
Have you checked the above suggestion?

Can you share me env_path

**Comment by chaharnitesh** [comment]
> Have you set the environment variable SECRET_KEY in .env file?
> If yes then you need to import .env file correctly
> I mean this one
> ---> env_path = Path(".") / ".env"
> instead of passing above line pass
> env_path = Path("crm") / ".env"

**Comment by chaharnitesh** [comment]
Yes i have followed 

import os
from dotenv import load_dotenv
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env_path = Path("crm") / ".env"
load_dotenv(dotenv_path=env_path)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRETKEY")

**Comment by chaharnitesh** [comment]
Yes i have followed your suggestion

here is the path:
import os
from dotenv import load_dotenv
from pathlib import Path
from celery.schedules import crontab

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env_path = Path("crm") / ".env"
load_dotenv(dotenv_path=env_path)

SECRET_KEY = os.getenv("SECRETKEY")

**Comment by Singhisbling** [comment]
Is it work for you ?

**Comment by chaharnitesh** [comment]
NO,Please advise what am I missed

**Comment by Singhisbling** [comment]
Where you have created the .env file ?
In crm folder or anywhere else

**Comment by chaharnitesh** [comment]
I created .env file under crm folder

**Comment by Singhisbling** [comment]
You closed the issue,
I think you got the solution, how did you fix that?

**Comment by alienpsp** [comment]
Hi I'm getting the exact issue, I'm added a .env in the crm folder but it's not helping, I've followed steps from the Readme.md and got stuck when running `python manage.py migrate` with the same django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

what other step am I missing?
