### ISSUE TITLE
cant run crm - 500 response

### ISSUE THREAD

**Issue by b1nslashsh** [MicroPyramid/Django-CRM#407]
installed as mentioned in [django-crm.readthedocs](https://django-crm.readthedocs.io/en/latest/)

what i have is 500 response in browser 

here is the server.log 
```
:/var/www/html/bottlecrm$ sudo -u postgres python3 manage.py runserver 192.168.43.98:8000
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2020 - 17:06:18
Django version 3.0.8, using settings 'crm.settings'
Starting development server at http://192.168.43.98:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/bottlecrm/common/views.py", line 93, in landing_page
    return render(request, "landing_page.html", status=200)
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/compressor/templatetags/compress.py", line 143, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/usr/local/lib/python3.8/dist-packages/compressor/templatetags/compress.py", line 111, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode)
  File "/usr/local/lib/python3.8/dist-packages/compressor/templatetags/compress.py", line 89, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/usr/local/lib/python3.8/dist-packages/compressor/cache.py", line 104, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/compressor/base.py", line 200, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/compressor/base.py", line 193, in mtimes
    return [str(get_mtime(value))
  File "/usr/local/lib/python3.8/dist-packages/compressor/base.py", line 193, in <listcomp>
    return [str(get_mtime(value))
  File "/usr/local/lib/python3.8/dist-packages/compressor/cache.py", line 110, in get_mtime
    mtime = cache.get(key)
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/memcached.py", line 180, in get
    val = self._cache.get(key)
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/memcached.py", line 171, in _cache
    self._client = self._lib.Client(self._servers, **client_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/memcache.py", line 215, in __init__
    self.set_servers(servers)
  File "/usr/local/lib/python3.8/dist-packages/memcache.py", line 291, in set_servers
    self.servers = [_Host(s, self.debug, dead_retry=self.dead_retry,
TypeError: 'NoneType' object is not iterable
[09/Oct/2020 17:06:28] "GET / HTTP/1.1" 500 189551
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 196, in finish_response
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/usr/lib/python3.8/wsgiref/simple_server.py", line 38, in close
    SimpleHandler.close(self)
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 335, in close
    self.result.close()
  File "/usr/local/lib/python3.8/dist-packages/django/http/response.py", line 253, in close
    signals.request_finished.send(sender=self._handler_class)
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/__init__.py", line 121, in close_caches
    cache.close()
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/memcached.py", line 98, in close
    self._cache.disconnect_all()
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/memcached.py", line 171, in _cache
    self._client = self._lib.Client(self._servers, **client_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/memcache.py", line 215, in __init__
    self.set_servers(servers)
  File "/usr/local/lib/python3.8/dist-packages/memcache.py", line 291, in set_servers
    self.servers = [_Host(s, self.debug, dead_retry=self.dead_retry,
TypeError: 'NoneType' object is not iterable
[09/Oct/2020 17:06:28] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('192.168.43.224', 60478)
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 196, in finish_response
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/usr/lib/python3.8/wsgiref/simple_server.py", line 38, in close
    SimpleHandler.close(self)
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 335, in close
    self.result.close()
  File "/usr/local/lib/python3.8/dist-packages/django/http/response.py", line 253, in close
    signals.request_finished.send(sender=self._handler_class)
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/__init__.py", line 121, in close_caches
    cache.close()
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/memcached.py", line 98, in close
    self._cache.disconnect_all()
  File "/usr/local/lib/python3.8/dist-packages/django/core/cache/backends/memcached.py", line 171, in _cache
    self._client = self._lib.Client(self._servers, **client_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/memcache.py", line 215, in __init__
    self.set_servers(servers)
  File "/usr/local/lib/python3.8/dist-packages/memcache.py", line 291, in set_servers
    self.servers = [_Host(s, self.debug, dead_retry=self.dead_retry,
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/dist-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/dist-packages/django/core/servers/basehttp.py", line 197, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 145, in run
    self.handle_error()
  File "/usr/local/lib/python3.8/dist-packages/django/core/servers/basehttp.py", line 119, in handle_error
    super().handle_error()
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 382, in handle_error
    self.finish_response()
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 288, in write
    self.send_headers()
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 345, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 358, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
```

**Comment by g3rb3n** [comment]
Same here.

**Comment by b1nslashsh** [comment]
@g3rb3n  still not working 
maybe you can help me with it!

```
Request Method: | GET
http://192.168.43.98:8000/
Django version = 3.0.8
TypeError
'NoneType' object is not iterable
/usr/local/lib/python3.8/dist-packages/memcache.py in set_servers, line 291
/usr/bin/python3
pyton version = 3.8.5
['/var/www/html/bottlecrm',  '/var/www/html/bottlecrm',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/dist-packages',  '/usr/lib/python3/dist-packages',  '/var/www/html/bottlecrm/crm/wsgi.py']
Fri, 23 Oct 2020 10:56:24 +0530
```

what was worng here any idea??

**Comment by b1nslashsh** [comment]
@g3rb3n hey thanks its working now :+1: 

cheers :beers:

**Comment by b1nslashsh** [comment]
@g3rb3n Which Django version is you used to run crm ? please replay 

thank you

**Comment by CrazyBunnyz** [comment]
how do you solve this issue ?

**Comment by CrazyBunnyz** [comment]
> @g3rb3n hey thanks its working now 👍
> 
> cheers 🍻

how do you solve this problem ?
