### ISSUE TITLE
sass' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by guru2582** [MicroPyramid/Django-CRM#410]
getting this error while trying to load home page. already installed all the requirements. not sure what is the issue.

Environment:

Request Method: GET
Request URL: http://localhost:8000/

Django Version: 3.0.8
Python Version: 3.8.5
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'simple_pagination',
 'compressor',
 'common',
 'accounts',
 'cases',
 'contacts',
 'emails',
 'leads',
 'opportunity',
 'planner',
 'sorl.thumbnail',
 'phonenumber_field',
 'storages',
 'marketing',
 'tasks',
 'invoices',
 'events',
 'teams']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'common.middleware.get_company.GetCompany']

Template error:
In template D:\Stuff\DjangoApps\dev\Django-CRM-master\templates\base.html, error at line 16
   'sass' is not recognized as an internal or external command,
operable program or batch file.

   6 :   <head>
   7 :     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   8 :     <meta charset="utf-8">
   9 :     <meta http-equiv="X-UA-Compatible" content="IE=edge">
   10 :     <meta name="viewport" content="width=device-width, initial-scale=1">
   11 :     <title>{{APPLICATION_NAME}}</title>
   12 :     <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
   13 :     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
   14 :     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
   15 : 
   16 :      {% compress css %} 
   17 :     <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
   18 :     <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
   19 :     {% endcompress %}
   20 :     {% block extralinks %} {% endblock %}
   21 :   </head>
   22 :   <body class="main_body_bg_color">
   23 :     <div class="wrapper">
   24 : 
   25 :       <header>
   26 :         <nav class="navbar navbar-expand-lg navbar-dark fixed-top">

Traceback (most recent call last):
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\base.py", line 282, in precompile
    mod = import_module(mod_name)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    <source code not available>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    <source code not available>
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    <source code not available>

During handling of the above exception (No module named 'sass {infile} {outfile}'), another exception occurred:
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Stuff\DjangoApps\dev\Django-CRM-master\common\views.py", line 93, in landing_page
    return render(request, "landing_page.html", status=200)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\templatetags\compress.py", line 143, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\templatetags\compress.py", line 119, in render_compressed
    rendered_output = compressor.output(mode, forced=forced, basename=file_basename)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\css.py", line 46, in output
    ret.append(subnode.output(*args, **kwargs))
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\css.py", line 48, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\base.py", line 314, in output
    output = '\n'.join(self.filter_input(forced))
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\base.py", line 254, in filter_input
    for hunk in self.hunks(forced):
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\base.py", line 228, in hunks
    precompiled, value = self.precompile(value, **options)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\base.py", line 287, in precompile
    return True, filter.input(**kwargs)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\filters\base.py", line 239, in input
    return super(CachedCompilerFilter, self).input(**kwargs)
  File "C:\Users\u13se\AppData\Local\Programs\Python\Python38\lib\site-packages\compressor\filters\base.py", line 206, in input
    raise FilterError(err)

Exception Type: FilterError at /
Exception Value: 'sass' is not recognized as an internal or external command,
operable program or batch file.

**Comment by b1nslashsh** [comment]
have you installed sass ??

`sudo gem install sass`??

**Comment by guru2582** [comment]
I am trying on windows PC , finally got it working but its not working in python virtual environment.

**Comment by jollypolly123** [comment]
Hi, don't know if you still need help on this but try npm install -g sass to install it globally
