### ISSUE TITLE
FATAL error upon setup: role 'xyz' doesn't exist

### ISSUE THREAD

**Issue by imsevak** [MicroPyramid/Django-CRM#440]
Hi there,
    after following all the instructions to setup the project when I try to run 
python manage.py migrate
I get error that role 'xyz' (my username on computer) doesn't exist. How can I resolve this issue? Entire backtrace is below....

Traceback (most recent call last):
  File "/home/mihir/crm/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/mihir/crm/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mihir/crm/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/mihir/crm/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mihir/crm/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/mihir/crm/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "xyz" does not exist

Thanks.

**Comment by RShehri** [comment]
If you just installed postgres or haven't used it on this machine before, then you probably need to create the role xyz via the psql prompt first.

**Comment by imsevak** [comment]
Thanks very much @RShehri . I will try this out over the weekend. I really appreciate this help.

**Comment by imsevak** [comment]
Hi @RShehri ,
     I was able to get past role doesn't exist by creating a role in postgres. Thanks for that hint. My next problem is upon running default configuration I am seeing page/resource not found on 17.0.0.1:8000/ any suggestions?

Thanks.
