### ISSUE TITLE
How to setup on cpanel?

### ISSUE THREAD

**Issue by KamranAbbasiDEV** [MicroPyramid/Django-CRM#442]
Any idea how to configure using cpanel??

![image](https://user-images.githubusercontent.com/48582481/127779430-4868730e-fe68-4869-8b0c-e6556e7ac777.png)

**Comment by KamranAbbasiDEV** [comment]
I did once, basically  application startup file would be manage.py and entrypoint would be entrypoint.sh right?

log file error: 

App 660 output: /opt/cpanel/ea-ruby27/root/usr/share/passenger/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 660 output:   import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 660 output: Traceback (most recent call last):
App 660 output:   File "/opt/cpanel/ea-ruby27/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
App 660 output:     app_module = load_app()
App 660 output:   File "/opt/cpanel/ea-ruby27/root/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
App 660 output:     return imp.load_source('passenger_wsgi', startup_file)
App 660 output:   File "/home/vendscon/virtualenv/crm.vendscon.com/3.7/lib64/python3.7/imp.py", line 171, in load_source
App 660 output:     module = _load(spec)
App 660 output:   File "<frozen importlib._bootstrap>", line 696, in _load
App 660 output:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
App 660 output:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
App 660 output:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
App 660 output:   File "/home/vendscon/crm.vendscon.com/passenger_wsgi.py", line 8, in <module>
App 660 output:     wsgi = imp.load_source('wsgi', 'manage.py')
App 660 output:   File "/home/vendscon/virtualenv/crm.vendscon.com/3.7/lib64/python3.7/imp.py", line 171, in load_source
App 660 output:     module = _load(spec)
App 660 output:   File "<frozen importlib._bootstrap>", line 696, in _load
App 660 output:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
App 660 output:   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
App 660 output:   File "<frozen importlib._bootstrap_external>", line 860, in get_code
App 660 output:   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
App 660 output:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
App 660 output:   File "manage.py", line 8
App 660 output:     def entrypoint.sh(environ, start_response):
App 660 output:                   ^
App 660 output: SyntaxError: invalid syntax
