### ISSUE TITLE
Traceback (most recent call last):     AttributeError: 'NoneType' object has no attribute 'Command'

### ISSUE THREAD

**Issue by RanaZain1998** [MicroPyramid/Django-CRM#446]
Every time I run it shows the error.
I tried many things but don't work

Traceback (most recent call last):
  File "E:\DJANGO-CRM-NEW\Django-CRM\manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\iamra\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 400, in execute_from_command_line
    utility.execute()
  File "C:\Users\iamra\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\iamra\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 244, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Users\iamra\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 38, in load_command_class
    return module.Command()
AttributeError: 'NoneType' object has no attribute 'Command'

**Comment by SametCobanoglu** [comment]
Hello Dear, did you solve your problem? I am facing the same problem right now.
